# Generated by Django 2.2.2 on 2019-09-14 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20190908_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyrecord',
            old_name='attendence',
            new_name='attendance',
        ),
    ]
