# Generated by Django 2.2.2 on 2019-09-14 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20190914_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stu_account',
            field=models.ForeignKey(blank=True, help_text='只有学员报名后方可为其创建账户', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.Customer', verbose_name='关联学员账号'),
        ),
    ]
