# Generated by Django 2.2.2 on 2019-09-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_userprofile_stu_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyrecord',
            name='score',
            field=models.SmallIntegerField(choices=[(100, 'A+'), (90, 'A'), (85, 'B+'), (75, 'B'), (70, 'C+'), (60, 'C'), (40, 'C-'), (-50, 'D'), (-100, 'copy'), (0, 'N/A')], default=0),
        ),
    ]
